[build]
  # Build command - use the optimized build script
  command = "./netlify-build.sh"
  
  # Publish directory - the built React app
  publish = "client/build"
  
  # Base directory - root of the project
  base = "."

[build.environment]
  # Node.js version for Netlify
  NODE_VERSION = "18"
  
  # Build environment
  NODE_ENV = "production"
  
  # Clear cache to avoid dependency issues
  NPM_FLAGS = "--no-optional --no-audit --no-fund"

# Functions configuration
[functions]
  directory = "netlify/functions"
  
  # Node.js version for functions
  node_bundler = "esbuild"

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Cache optimization for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache optimization for HTML files
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Cache optimization for service worker
[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Cache optimization for manifest
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
