[build]
  # Build command for the frontend
  command = "cd client && npm run build"
  
  # Directory to publish (the built React app)
  publish = "client/build"
  
  # Base directory for the build context
  base = "."

[build.environment]
  # Node.js version for the build
  NODE_VERSION = "18"
  
  # Set environment variables
  NODE_ENV = "production"
  REACT_APP_API_URL = "https://your-backend-domain.com"

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers for HTML files
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Functions (if you want to add serverless functions later)
[functions]
  directory = "netlify/functions"
